config/routes.rb
Rails.application.routes.draw do
  resources :trains do
    resources :waggons, shallow: true
  end
  resources :routes
  resources :railway_stations do
    patch :update_position, on: :member
    patch :update_arrival, on: :member
    patch :update_departure, on: :member
  end

  root 'railway_stations#index'
end

app/models/waggon.rb
class Waggon < ApplicationRecord
  belongs_to :train

  validates :number, presence: true, uniqueness: { scope: :train_id }
  before_validation :set_number

  TYPES = { EconomyWaggon => 'Economy',
            SleeperWaggon => 'Sleeper',
            SittingWaggon => 'Sitter',
            LuxeWaggon    => 'Luxe' }.freeze

  scope :head, -> { order(:number) }
  scope :tail, -> { order(:number).reverse_order }

  def set_number
    self.number ||= train.waggons.maximum(:number).to_i + 1
  end

  def grab_types
    TYPES.map { |k, v| v if k.to_s == type }
  end
end

app/controllers/waggons_controller.rb
class WaggonsController < ApplicationController
  before_action :set_waggon, only: [:show, :edit, :update, :destroy]
  before_action :set_train, only: [:new, :create]

  def index
    @waggons = Waggon.all
  end

  def show
    @waggon = Waggon.find(params[:id])
  end

  def new
    @waggon = Waggon.new
  end

  def create
    @waggon = @train.waggons.new(waggon_params)

    if @waggon.save
      redirect_to @train
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @waggon.update(waggon_params)
      redirect_to waggon_path(@waggon)
    else
      render :edit
    end
  end

  def destroy
    @waggon.destroy
    redirect_to waggons_path
  end

  private

  def set_train
    @train  = Train.find(params[:train_id])
  end

  def set_waggon
    @waggon = Waggon.find(params[:id])
  end

  def waggon_params
    params.require(:waggon).permit(:type, :upper_shelf, :lower_shelf, :side_upper_shelf, :side_lower_shelf, :train_id,
                                   :seat, :number)
  end
end

app/views/waggons/_economy_waggon.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Waggon:</strong>

<ul>
  <li><i>Number</i>: <%= @waggon.number %></li>
  <li><i>Type</i>: <%= @waggon.type %></li>
  <li><i>Upper shelves</i>: <%= @waggon.upper_shelf %></li>
  <li><i>Lower shelves</i>: <%= @waggon.lower_shelf %></li>
  <li><i>Side upper shelves</i>: <%= @waggon.side_upper_shelf %></li>
  <li><i>Side lower shelves</i>: <%= @waggon.side_lower_shelf %></li>
  <li><i>Train:</i> <%= @waggon.train.number %></li>
</ul>

app/views/waggons/_form.html.erb
<%= form_for [@train, @waggon] do |form| %>
<%#= form_for  @waggon.becomes(Waggon) do |form| %>

  <%= render 'common/errors', resource: @waggon %>

  <div>
    <p>
      <%= form.label :type, "Waggon type" %>
      <%= form.select :type, Waggon::TYPES.invert.map { |k, v| [k.to_s, v] } %>
    </p>

    <p>
      <%= form.label :upper_shelf, "Amount of upper shelves" %>
      <%= form.number_field(:upper_shelf, in: 1 .. 36) %>
    </p>

    <p>
      <%= form.label :lower_shelf, "Amount of lower shelves" %>
      <%= form.number_field(:lower_shelf, in: 1 .. 36) %>
    </p>

    <p>
      <%= form.label :side_upper_shelf, "Amount of side upper shelves" %>
      <%= form.number_field(:side_upper_shelf, in: 1 .. 36) %>
    </p>

    <p>
      <%= form.label :side_lower_shelf, "Amount of side lower shelves" %>
      <%= form.number_field(:side_lower_shelf, in: 1 .. 36) %>
    </p>

    <p>
      <%= form.label :seat, "Amount of seats" %>
      <%= form.number_field(:seat, in: 1 .. 36) %>
    </p>

  </div>

  <div class="actions">
    <%= form.submit 'Create' %>
  </div>
<% end %>

app/views/waggons/_luxe_waggon.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Waggon:</strong>

<ul>
  <li><i>Number</i>: <%= @waggon.number %></li>
  <li><i>Type</i>: <%= @waggon.type %></li>
  <li><i>Lower shelves</i>: <%= @waggon.lower_shelf %></li>
  <li><i>Train:</i> <%= @waggon.train.number %></li>
</ul>

app/views/waggons/_sitting_waggon.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Waggon:</strong>

<ul>
  <li><i>Number</i>: <%= @waggon.number %></li>
  <li><i>Type</i>: <%= @waggon.type %></li>
  <li><i>Seats</i>: <%= @waggon.seat %></li>
  <li><i>Train:</i> <%= @waggon.train.number %></li>
</ul>

<%= link_to 'Edit', edit_waggon_path(@waggon) %> |
<%= link_to 'Back', waggon_path %>

app/views/waggons/_sleeper_waggon.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Waggon:</strong>

<ul>
  <li><i>Number</i>: <%= @waggon.number %></li>
  <li><i>Type</i>: <%= @waggon.type %></li>
  <li><i>Upper shelves</i>: <%= @waggon.upper_shelf %></li>
  <li><i>Lower shelves</i>: <%= @waggon.lower_shelf %></li>
  <li><i>Train:</i> <%= @waggon.train.number %></li>
</ul>

<%= link_to 'Edit', edit_waggon_path(@waggon) %> |
<%= link_to 'Back', waggon_path %>

app/views/waggons/_waggon.html.erb
<tr>
  <td><%= waggon.number %></td>
  <td><%= link_to 'Show', waggon_path(waggon) %></td>
  <td><%= link_to 'Edit', edit_waggon_path(waggon) %></td>
  <td><%= link_to 'Delete', waggon_path(waggon), method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/waggons/edit.html.erb
<h1>Edit Waggon</h1>

<%= render 'form', waggon: @waggon %>

<%= link_to 'Show', waggon: @waggon %> |
<%= link_to 'Back', train: @waggon.train %>

app/views/waggons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Waggons</h1>

<table>
  <thead>
  <tr>
    <th>Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>
  <%= render partial: 'waggon', collection: @waggons, as: :waggon %>
  <tbody>

  </tbody>
</table>

<p><%= link_to 'New waggon', new_train_waggon_path %></p>

app/views/waggons/new.html.erb
<h1>New Waggon</h1>

<%= render 'form' %>

<%= link_to 'Back', train_waggons_path %>

app/views/waggons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Waggon type</strong>
  <%= @waggon.grab_types.compact.join("") %>
  <%= render @waggon.type.underscore %>
</p>

<%= link_to 'Edit', edit_waggon_path(@waggon) %> |
<%= link_to 'Back to the train', @waggon.train%>