config/routes.rb
Rails.application.routes.draw do
  resources :trains do
    resources :waggons, shallow: true
  end
  resources :routes
  resources :railway_stations do
    patch :update_position, on: :member
    patch :update_arrival, on: :member
    patch :update_departure, on: :member
  end

  root 'railway_stations#index'
end

app/models/train.rb
class Train < ApplicationRecord

  has_many :tickets
  has_many :waggons

  belongs_to :current_station, class_name: 'RailwayStation', foreign_key: :current_station_id
  belongs_to :route

  validates :number, presence: true

  def waggons_count(type_of_waggon)
    waggons.where(type: type_of_waggon).count
  end

  def seats_count(type_of_waggon, type_of_shelf)
    waggons.where(type: type_of_waggon).sum(type_of_shelf)
  end
end

app/controllers/trains_controller.rb
class TrainsController < ApplicationController
  before_action :set_train, only: %i[show edit update destroy]

  # GET /trains
  # GET /trains.json
  def index
    @trains = Train.all
  end

  # GET /trains/1
  # GET /trains/1.json
  def show
  end

  # GET /trains/new
  def new
    @train = Train.new
  end

  # GET /trains/1/edit
  def edit
  end

  # POST /trains
  # POST /trains.json
  def create
    @train = Train.new(train_params)

    respond_to do |format|
      if @train.save
        format.html { redirect_to @train, notice: 'Train was successfully created.' }
        format.json { render :show, status: :created, location: @train }
      else
        format.html { render :new }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /trains/1
  # PATCH/PUT /trains/1.json
  def update
    respond_to do |format|
      if @train.update(train_params)
        format.html { redirect_to @train, notice: 'Train was successfully updated.' }
        format.json { render :show, status: :ok, location: @train }
      else
        format.html { render :edit }
        format.json { render json: @train.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trains/1
  # DELETE /trains/1.json
  def destroy
    @train.destroy
    respond_to do |format|
      format.html { redirect_to trains_url, notice: 'Train was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_train
    @train = Train.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def train_params
    params.require(:train).permit(:number, :current_station_id, :route_id, :sort)
  end
end

app/helpers/trains_helper.rb
module TrainsHelper
end

app/views/trains/_form.html.erb
<%= form_with(model: @train, local: true) do |form| %>
  <%= render 'common/errors', resource: @train %>

  <div class="field">
    <%= form.label :number %>
    <%= form.text_field :number, id: :train_number %>
  </div>

  <div>
    <%= form.label :current_station, "Current station" %>
    <%= form.collection_select :current_station_id, RailwayStation.all, :id, :title %>
  </div>

  <div>
    <%= form.label :route, "Choose route" %>
    <%= form.collection_select :route_id, Route.all, :id, :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/trains/_train.html.erb
<tr>
  <td><%= train.number %></td>
  <td><%= link_to 'Show', train %></td>
  <td><%= link_to 'Edit', edit_train_path(train) %></td>
  <td><%= link_to 'Destroy', train, method: :delete, data: { confirm: 'Are you sure?' } %></td>
</tr>

app/views/trains/edit.html.erb
<h1>Editing Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Show', @train %> |
<%= link_to 'Back', trains_path %>

app/views/trains/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Trains</h1>

<table>
  <thead>
  <tr>
    <th>Number</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <%= render @trains %>
  </tbody>
</table>

<br>

<%= link_to 'New Train', new_train_path %>

app/views/trains/new.html.erb
<h1>New Train</h1>

<%= render 'form', train: @train %>

<%= link_to 'Back', trains_path %>

app/views/trains/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Number</strong></br>
  <%= @train.number %>
</p>

<strong>Station</strong></br>
<% if @train.current_station.present? %>
  <%= @train.current_station.title %>
<% else %>
  No current station
<% end %>
</p>

<p><strong>Route</strong></br>
  <% if @train.route.present? %>
    <%= @train.route.name %>
  <% else %>
    No route
  <% end %>
</p>

<p><%= link_to "Add a waggon", new_train_waggon_path(@train) %></p>

<%= form_with(model: @train, local: true) do |form| %>

  <strong>Waggons</strong></br>
  <% if @train.waggons.present? %>
    <%= "Amount of waggons:" %>
    <%= @train.waggons.count %>
    <p><%= form.submit "Sort" %>
      <i><%= "sort by tails?" %></i>
      <%= form.check_box :sort %></p>
    <p>
      <% if !@train.sort %></p>
        <% @train.waggons.head.each do |waggon| %>
          <%= link_to waggon.number, waggon_path(waggon) %>
        <% end %>
      <% else %>
        <% @train.waggons.tail.each do |waggon| %>
          <%= link_to waggon.number, waggon_path(waggon) %>
        <% end %>
      <% end %>
  <% end %>

  <p><%= link_to 'Edit', edit_train_path(@train) %> |
    <%= link_to 'Back', trains_path %></p>
<% end %>