config/routes.rb
Rails.application.routes.draw do
  resources :trains do
    resources :waggons, shallow: true
  end
  resources :routes
  resources :railway_stations do
    patch :update_position, on: :member
    patch :update_arrival, on: :member
    patch :update_departure, on: :member
  end

  root 'railway_stations#index'
end

app/models/route.rb
class Route < ApplicationRecord

  has_many :railway_stations_routes
  has_many :railway_stations, through: :railway_stations_routes
  has_many :trains

  validates :name, presence: true
  validate :stations_count

  before_validation :set_name

  scope :sort_by_station, ->(route_id) { RailwayStationsRoute.order(:position) }

  private

  def set_name
    self.name ||= "#{railway_stations.first.title} - #{railway_stations.last.title}"
  end

  def stations_count
    if railway_stations.size < 2
      errors.add(:base, "Route should contain at least two stations")
    end
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  def index
    @routes = Route.all
  end

  def show
  end

  def new
    @route = Route.new
  end

  def create
    @route = Route.new(route_params)

    if @route.save
      redirect_to @route
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @route.update(route_params)
      redirect_to @route
    else
      render :edit
    end
  end

  def destroy
    @route.destroy
    redirect_to routes_path
  end

  private

  def set_route
    @route = Route.find(params[:id])
  end

  def route_params
    params.require(:route).permit(railway_station_ids: [])
  end
end

app/views/routes/_form.html.erb
<%= form_with(model: @route, local: true) do |form| %>
  <%= render 'common/errors', resource: @route %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :railway_station_ids, "Current station" %>
    <%= form.collection_select :railway_station_ids, RailwayStation.all, :id, :title, {}, { multiple: true } %>
  </div>


  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Edit Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Routes</h1>

<table>
  <thead>
  <tr>
    <th>Name</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @routes.each do |route| %>
    <tr>
      <td><%= route.name %></td>
      <td><%= link_to 'Show', route %></td>
      <td><%= link_to 'Edit', edit_route_path(route) %></td>
      <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Route', new_route_path %>

app/views/routes/new.html.erb
<h1>New Route</h1>

<%= render 'form' %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @route.name %>
</p>

<p>
  <strong>Stations in the route:</strong>
</p>

<p>
  <% if @route.railway_stations.empty? %>
    Route has no stations
  <% else %>
  <table>
    <thead>
    <tr>
      <td width="100px">Title</td>
      <td>Position</td>
      <td>Arrival</td>
      <td>Departure</td>
    </tr>
    </thead>
    <tbody>
    <% @route.railway_stations.ordered.each do |station| %>
      <tr>
        <td><%= station.title %></td>
        <td>
          <%= form_tag update_position_railway_station_path(station), method: :patch do %>
            <%= number_field_tag :position, station.position_in(@route) %>
            <%= hidden_field_tag :route_id, @route_id %>
            <%= submit_tag "Update" %>
          <% end %>
        </td>
        <td>
          <%= form_tag update_arrival_railway_station_path(station), method: :patch do %>
            <%= time_field_tag :arrival_date, station.time_in(@route) %>
            <%= hidden_field_tag :route_id, @route_id %>
            <%= submit_tag "Update" %>
          <% end %>
        </td>
        <td>
          <%= form_tag update_departure_railway_station_path(station), method: :patch do %>
            <%= time_field_tag :departure_date, station.time_in(@route) %>
            <%= hidden_field_tag :route_id, @route_id %>
            <%= submit_tag "Update" %>
          <% end %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
<% end %>
</p>

<p>
  <strong>Trains in the route:</strong>
</p>

<p>
  <% if @route.trains.empty? %>
    Route has no trains
  <% else %>
  <ul>
    <% @route.trains.each do |train| %>
      <li><%= train.number %></li>
    <% end %>
  </ul>
<% end %>
</p>


<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>